project:
  type: website

website:
  title: "Quarto Book"
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - Day 1 Part 2

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
