project:
  type: website

website:
  title: "My Project Name"
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - your-other-file.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
